on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - run: npm ci
      - run: npm run lint
      - run: npm run test
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Run a pipeline with variables as object
        uses: refactr/action-run-pipeline@master
        with:
          project_id: 61c21b61ce610a30584b4636
          job_id: 61cb340ed42b9b0d71836560
          api_token: '${{ secrets.MAIN_API_TOKEN }}'
          api_url: 'https://api.main.refactr.it/v1'
